### ISSUE TITLE
Add support for itunes:summary field in items

### ISSUE THREAD

**Issue by madhead** [ivanisidrowu/KtRssReader#67]
Take a look at the [feed](http://insidejava.libsyn.com/rss) of Inside Java podcast:

```xml
<item>
    <title>#12 - “jpackage” with Kevin Rushforth</title>
    <itunes:title>“jpackage” with Kevin Rushforth</itunes:title>
    <pubDate>Thu, 11 Feb 2021 11:57:06 +0000</pubDate>
    <guid isPermaLink="false"><![CDATA[c0cdd551-0fc0-4eaa-bccf-e43360ed04a9]]></guid>
    <link><![CDATA[https://inside.java/2021/02/11/podcast-012/]]></link>
    <itunes:image href="http://static.libsyn.com/p/assets/f/8/0/a/f80a626bd25156f4/Inside_Java_Apple_Podcast_3000_tile.png" />
    <description><![CDATA[…]]></description>
    <content:encoded><![CDATA[…]]></content:encoded>
    <enclosure length="20706817" type="audio/mpeg" url="http://traffic.libsyn.com/insidejava/InsideJava-Ep012.mp3?dest-id=2318780" />
    <itunes:duration>25:07</itunes:duration>
    <itunes:explicit>clean</itunes:explicit>
    <itunes:keywords>distribution,packaging,jdk,openjdk,jdk16</itunes:keywords>
    <itunes:subtitle><![CDATA[…]]></itunes:subtitle>
    <itunes:summary>…</itunes:summary>
    <itunes:season>1</itunes:season>
    <itunes:episode>12</itunes:episode>
    <itunes:episodeType>full</itunes:episodeType>
    <itunes:author>David Delabassee, Kevin Rushforth</itunes:author>
</item>
```

They use HTML markup for descriptions, but they have the same text in `itunes:summary` and `itunes:subtitle`, but without any tags. It would be really great to support them.

**Comment by madhead** [comment]
I've made a PR, but it's kind of a blind shot: I don't see any CI here, so it won't probably work. Feel free to take that piece of code, or tell me what should also add in this PR. Probably, something should me also touched for Android?

**Comment by madhead** [comment]
`./gradlew clean check` passed

**Comment by ivanisidrowu** [comment]
I've checked the PR and gone through tests, it looks good to me. I will modify the document once the PR merged into master. Thanks, @madhead!

> I've made a PR, but it's kind of a blind shot: I don't see any CI here, so it won't probably work. Feel free to take that piece of code, or tell me what should also add in this PR. Probably, something should be also touched for Android?
