### ISSUE TITLE
Info about contact

### ISSUE THREAD

**Issue by anovinc** [ivanisidrowu/KtRssReader#73]
How can I contact someone, I have problem with custom data and reader. My reader for my data class isn't generated but I don't know why. If you have advice or can help I would appreciate that.

**Comment by ivanisidrowu** [comment]
Hi, if you still can't solve the problem, you can provide more information about the data class and the sample code of you data. We will look up into them.

**Comment by anovinc** [comment]
https://github.com/anovinc/KtRssReader
Here is my code, problem is that compiler can't recognize NewsReader so I
can't use that class. Thank you very much.

Cheers.

čet, 30. pro 2021. u 04:34 Ivan ***@***.***> napisao je:

**Comment by ivanisidrowu** [comment]
Hi @anovinc ,

I looked up the code and found that the root element name of the `News` class is not `@RssTag(name = "channel")`, it's `@RssTag(name = "item")`. Please refer to the [sample](https://github.com/anovinc/KtRssReader/blob/master/app/src/main/java/com/example/rss_reader/News.kt#L6).
You can add a data class that represents the root channel tag. It could be something like ...

```kotlin
@RssTag(name = "channel")
data class RssRawData(
    val description: String?,
    @RssTag(name = "item")
    val list: List<News>
) : Serializable

@RssTag("item")
data class News(
    val title: String?,
    @RssTag("thumbnail")
    val imageURL: String?,
    val link: String?
): Serializable
```

The current version of the library only generates readers for the root element that has the name of "channel" on it.
We designed readers specifically for reading and caching the podcast channels, but I will discuss this perspective with my team members to decide should we add this feature or not. Once I have the updated version of the lib, I will comment under this issue to let you know.

Although in the current version, you can't use the generated readers with the non-channel root tag, you still can use the generated parsers. For example, if you build with [the sample](https://github.com/anovinc/KtRssReader/blob/master/app/src/main/java/com/example/rss_reader/News.kt#L6), you can find the parsers under `tw.ktrssreader.generated.NewsParser`. It parses the RSS source for you. :)

By the way, the Gradle dependencies don't have `com.github.ivanisidrowu.KtRssReader:android:v2.1.2`, please make sure [it](https://github.com/anovinc/KtRssReader/blob/master/app/build.gradle#L61) checks out the android version of the lib.

Thanks!

**Comment by anovinc** [comment]
Thank you very much.

uto, 4. sij 2022. 13:12 Ivan ***@***.***> je napisao:
