### ISSUE TITLE
Unexplained 403 results with Buzzsprout-hosted RSS feeds

### ISSUE THREAD

**Issue by christate** [ivanisidrowu/KtRssReader#83]
KtRssReader incurs a 403 when trying to fetch Buzzsprout-hosted feeds.  It's unclear why this happens:  the feeds appear fine to web browsers like Chrome or Edge; and similarly fine when fetched with command-line tools such as `curl`.

Example of a failing feed:
https://feeds.buzzsprout.com/1112270.rss

(It's particularly unfortunate because some quite high-profile podcasts are hosted there.)

**Comment by christate** [comment]
It looks like the issue is that Buzzsprout rejects GET requests that do not provide a User-Agent header, and the way that KtRssReader uses OkHttp means that the GETs are sent without one.

**Comment by dev-weiqi** [comment]
@ivanisidrowu Should we allow users to customize headers in OkHttp?

**Comment by ivanisidrowu** [comment]
Yeah, I will try to work on that.
